[package]
name = "paramacode/input-intent"
description = "Intent-driven input runtime for Roblox with contextual action management, buffering, interruption, rebinding, and network-ready gameplay flows. Built with roblox-ts."
license = "MIT"
author: ["paramacode"],
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = [
  "src/**",
  "out/**",
  "LICENSE.txt",
  "README.md",
  "wally.toml"
]

exclude = [
  "node_modules/**",
  ".vscode/**",
  "docs/**",
  "*.toml",
  "*.json",
  "*.tgz"
]

[dependencies]
